name: yolo

description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
    
  flutter_web_plugins:
    sdk: flutter
 

  # ğŸ”¥ Firebase - versions stables
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.0.3

  # ğŸ“¦ Packages utiles
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  share_plus: ^10.0.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  import_sorter: ^4.6.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.4
  geocoding: ^3.0.0
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.2.2
  table_calendar: ^3.0.9
  google_mobile_ads: ^5.0.0
  rxdart: ^0.27.7
  http: ^1.1.0
  geolocator: ^10.0.0
  url_launcher: ^6.2.6
  audioplayers: ^5.2.1
  record: ^4.4.0
  path_provider: ^2.1.2
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  web: ^1.0.0
  flutter_html: ^3.0.0
  webview_flutter: ^4.13.0
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/cities/
    - assets/regions/
    - assets/images/
    - assets/images/placeholder.jpg
    - assets/images/default_group.png

